### ISSUE TITLE
Get filtered values

### ISSUE THREAD

**Issue by ponasromas** [ikkez/f3-validation-engine#11]
How to get filtered values?

```
$data = [
  'username' => 'Jonny',
  'email' => 'john.doe@domain.com',
];
$rules = [
  'username' => [
    'filter' => 'trim',
    'validate' => 'required|min_len,10|max_len,128|unique',
  ],
  'email' => [
    'filter' => 'trim',
    'validate' => 'required|valid_email|email_host',
  ]
];
$valid = $validation->validate($rules, $data);
```

Returns only TRUE/FALSE. In GUMP there was approach like this:

`$valid = $validation->validate($rules, $data);`

if validation was "TRUE", than `$valid['username']` return filtered value. How to achieve this?

**Comment by ikkez** [comment]
the filter is automatically applied to $data. As `$data` is handled as reference, the filter is already applied to $data after calling this function.

**Comment by ponasromas** [comment]
Aha, got it. A bit magical :) but convenient.
