### ISSUE TITLE
Problem with regex

### ISSUE THREAD

**Issue by jvenkat74** [ikkez/f3-validation-engine#7]
Hi:

  Am trying to integrate f3-cortex and f3-validation-engine with our project.

  The fieldConf is specified as an ini. The following configuration for "validate" rule does not work

devno.validate="required|regex,/^[1-9][0-9]{0,2}:[1-9][0-9]{0,2}$/"

 It crashes with following error message

** START
preg_match(): No ending delimiter '/' found
[/opt/lib/vendor/ikkez/f3-validation-engine/src/gumpy.class.php:2012] preg_match()
** END

   whereas the following rule works.
   
devno.validate="required|regex,/^[1-9][0-9]?[0-9]?:[1-9][0-9]?[0-9]?$/"

   Using 1.7 (latest version). Looks like ","in "{0,2}" is causing problem. Pl look into this and fix. If you do need any more details, please let me know.

**Comment by ikkez** [comment]
fixed in 1.7.2
